### ISSUE TITLE
Mod Addition/Removal Suggestion Thread

### ISSUE THREAD

**Issue by UnNinja** [BreakfastCraft/BreakfastBuffet#70]
[Project Red (world generation module)](http://www.curse.com/mc-mods/minecraft/229049-project-red-world). ProjectRed has started adding some redpower2 machines, but they require the dust stuff and sapphires. Also volcanoes are cool. 

[Big Doors](http://www.curse.com/mc-mods/minecraft/232398-big-doors) Adds 3x3 versions of the vanilla/1.8 doors. Allows for grander entrances and odd block length walls. 

[Extra Cells](http://www.curse.com/mc-mods/minecraft/229218-extracells2) This was previously passed over because it wasn't being updated, it looks like someone has picked it back up. 

[FTB Utilities](http://www.curse.com/mc-mods/minecraft/237102-ftb-utilities) was recently updated to include options for chunk loading, among a plethora of existing and incoming features. 

[Botanical Addons](http://minecraft.curseforge.com/projects/botanical-addons) Adds a bunch of nice cosmetic blocks to botania.

**Comment by Sansu11** [comment]
A bit late for me to add to this since I'm sure you guys are already well underway in Dev of the next update but, here are a few more suggestions.

[http://www.curse.com/mc-mods/minecraft/223666-thaumic-energistics](Thaumic Energistics) Was previously removed since it wasn't being updated. Seems like it's being updated now.

[http://www.curse.com/mc-mods/minecraft/237271-gadomancy](Gadomancy) Gadomancy adds a lot of thaumcraft automation. Dunno if ya'll were planning to update to Thaum5, but if not this would make people hate thaum a little less.

[http://www.curse.com/mc-mods/minecraft/240562-practical-logistics](Practical Logistics) Quality of life addition that I think would work well with AE2

[http://www.curse.com/mc-mods/minecraft/232192-thaumic-bases#t1:screenshots](Thaumic Bases) I'm a Thaumcraft junkie. Adds a lot of cool things from previous version of Thaum.

[http://www.curse.com/mc-mods/minecraft/220308-thaumic-infusion](Thaumic Infusion) Adds a lot of infusions for world blocks. Like making a block emit light.

**Comment by slidingmike** [comment]
@Sansu11 Have you played with any of these mods yet? In a pack environment? Any known issues you could recall if there was any?

**Comment by Sansu11** [comment]
@slidingmike The only two I haven't played in a pack environment are Gadomancy and Practical Logistics. Overall I didn't find any bugs, but I wasn't pushing mod interactions to see if I could force any.

**Comment by demethan** [comment]
@UnNinja  

Project Red (world generation module)  = probably
Big Doors = I agree
Extra Cells = I agree
FTB Utilities = it will be
Botanical Addons = probably

@Sansu11 

Thaumic Energistics = probably
Gadomancy = seems ok 
Practical Logistics = NO, unstable says the forum
Thaumic Bases = seems fine
Thaumic Infusion = seems to be only for 1.8.9, I don`t see 1.7.10


I would like to add 

NoMoreRecipeConflict = fixes recipe conflict on the fly
Tick Profiler to the server side download

**Comment by slidingmike** [comment]
I don't think we should do Project Red. The mod seems to be very iffy on its builds. There's another mod I was playing around with on Juice which is called MCI Craft.

**Comment by slidingmike** [comment]
#73

**Comment by slidingmike** [comment]
#69 Suggestion: Agricraft Addition, Magical Crops Removal

**Comment by demethan** [comment]
#53 IC2 - RF api bridge.

**Comment by slidingmike** [comment]
Removal: ReactorCraft or Big Reactors
Addition: Advanced Generators

**Comment by waerloga** [comment]
Merge Breakfast Buffet, Breakfast Special, Spilled Juice into one ober-kitchen sink pack.

**Comment by demethan** [comment]
ReactorCraft stays
Advanced Generator is already in BB

**Comment by demethan** [comment]
No more suggestions. Locked in
